### PR TITLE
Adding lestec info to readme

### PR DESCRIPTION
**Pull request by lestec**
Added instructions and started the first reply.

### CODE REVIEW

**Comment by chrisvneal** [comment]
Hey, what's up. I was thinking of how the team would go about merging their changes and it would probably be best to either 

* **create our own local dev branch** and _pull request_ those changes to **this dev branch** or
* as this is a "practice" repo, we could possibly **initialize a new production repo** (possibly as an [organization](https://github.com/blog/674-introducing-organizations))with a finalized version of this README as the _initial commit_, and push changes to a branch off of it, possibly still named **dev**

## Quick Notes
* I made changes to the **README** file and will push them to you as a pull request as soon as we get that cleared up because it's ready to go! 

* Can you look into adding me as a contributor with merge privileges? I'm thinking about being on the **Git Assistance** team I created along with yourself (you can view that in the new README that I'm pushing)

* For some reason when I cloned my fork on my machine, it didn't come with the dev branch. I don't think subsequent branches ever do, but I still found a way to check it out onto my computer. Do  you remember why it does that?

Let me know when you're up and running! I may just create a pull request shortly anyway so that you can view my changes and merge/discuss as necessary.

**Comment by lestec** [comment]
Great ideas! I will be on this midmorning and this afternoon. Just message
me when you are ready and we can work on this ☺

**Comment by lestec** [comment]
Also there is a command to see all the branches on the screen it's git
branch -a. On mine it shows them in a red color.
Next checkout the dev branch, then run git branch -a again and you should
see it.
Let me know if this helps.


On Feb 27, 2018 9:39 AM, "leslie tecumseh" <lestec076@gmail.com> wrote:

Great ideas! I will be on this midmorning and this afternoon. Just message
me when you are ready and we can work on this ☺

**Review by chrisvneal — COMMENTED** [review]
Everything looks good with this, I made modifications to the whole README.md file, though. Let's use that, thats' where all the info will be.

**Comment by chrisvneal** [comment]
I'm going to close this pull request and merge the new README into the master.

**Pull request closed without merging**
