### PR TITLE
updating dev

### PR DESCRIPTION
**Pull request by lestec**
Was behind 2 commits so merging branch with master so its up to date.

### CODE REVIEW

**Comment by chrisvneal** [comment]
What branch are you saying was behind two commits? Your **dev** branch was behind?

**Comment by lestec** [comment]
Hi, yes my dev branch. It looks the same now, but because I did it on
GitHub there is a compare &pull request( I should of done it in my
terminal). I don't think I need this now but I can't figure out how to
delete it. I could do a pull request then deny it?

**Comment by chrisvneal** [comment]
### Here's how I'm trying to keep things simple on my end:

I have three branches on my fork right now

* **master**
* **dev**
* **chrisneal-dev**

The `master` branch should always be updated with the latest changes, any commits to the repo would obviously be ahead. Nonetheless, it is current from a contributors perspective and that's where they should pull from. _I should add this part in the **README**_

>It is the job of the contributor to pull the latest changes before making changes and pushing them

They _should_ be able to do this in their local terminal by 

1. **coding** `git remote add upstream https://github.com/lestec/GWGpractice`

2. **Switching** to a another _topic branch_ to make changes on

3. **Pushing those changes** to their local fork by coding:
 
`git push -u origin [whatever they named their branch]`

4. **Going online and creating a pull request** for that branch to be pulled into **GWGpractice/dev** which will be reviewed before doing so. We will update the **master** branch periodically with major changes so our contributors pull current code when they pull from the upstream

For example, I would make changes on my local **chrisneal-dev**, push them to my forked repo and make a pull request from there into **GWGpractice/dev**. If those changes get merged, I would have to go to my local copy and pull from that new updated master into my code as well. Either that or merge from my local [chrisneal-dev] that I pushed since they both have the same commits now anyway. _Get that?_ 

Ideally, whenever we want to look at and change code, we should pull from the **upstream master** _(the master branch on your account)_ in case someone else has submitted and merged code since our last commit.

**Comment by lestec** [comment]
Hi take a look at this, it explains better what I'm trying to say.
https://github.com/W8sconsin/studentlist/blob/master/contributing.md

**Comment by lestec** [comment]
This is a great tool for git.
https://www.gitkraken.com

**Comment by chrisvneal** [comment]
Oh wow, going to try that tool out. I found that these GUI git tools are helping me learn what's actually going on under the hood a lot. 

**Are you using the GitHub Desktop tool?**

I have it downloaded, but haven't used it yet. I wanted to wait until I learned the system here a little.

That **contributing.md** file is pretty much on point to how we should work, pull requesting to the **dev** branch., We should be all set up for this workflow now. Remember, no one else's set up is our concern. Here, we worry about the code that's making a pull request and ensuring its going into **dev** first.

All we do now, unless we make changes is wait for people who are interested to start joining teams and making this happen. In a couple days, if nothing is going on, I'm going to start another post in the Forums and Slack again and that's it. But I do hope this project doesn't have too many contributors... yet.

## Quick Notes

* Once I read into it, I think [creating an organization](https://help.github.com/articles/about-organizations/) will be the best way to go instead of hosting everything on your personal page which is fine for now, thank you. There should be an easy way to incorporate what we've done so far.

**Pull request merged**
